sudo: required
dist: trusty

language: cpp

python:
  - '2.7.11'

#before_install:
  # Try to get python2.7 with UCS4 : https://github.com/travis-ci/travis-ci/issues/4948#issuecomment-165779970
  #- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

script:
  - g++ --version
  - cmake --version
  - docker --version
  - python2.7 --version
  - python2.7 -c "import sys; print ('UCS4 build' if sys.maxunicode > 65535 else 'UCS2 build')"
